// SPDX-License-Identifier: MIT
pragma solidity ^0.8.23;

/// @dev Mock Verdikta Aggregator for tests (ETH payment rail).
///      Lets the test harness pre-set evaluation results, control maxTotalFee, and
///      simulate the ethOwed refund credit / withdrawEth pull-payment ledger.
contract MockVerdiktaAggregator {
    uint256 public feeMultiplier = 3; // maxTotalFee = input * multiplier
    uint256 public refundAmount;      // ETH (wei) credited to ethOwed[requester] (default 0)
    bool    public creditOnTimeout;   // if true, the refund is credited at finalizeEvaluationTimeout
                                      // (settlement) rather than at request time — models a round
                                      // whose prepay stays reserved until timed out + settled.

    struct Result {
        uint256[] scores;
        string    justificationCids;
        bool      exists;
    }

    mapping(bytes32 => Result) private _results;
    mapping(address => uint256) public ethOwed;
    mapping(bytes32 => address) public requesterOf; // aggId -> requester (the EvaluationWallet)
    mapping(bytes32 => bool) public settled;        // aggId -> already settled via timeout
    uint256 private _nonce;

    // --- Test helpers ---

    /// @dev Pre-set the result that getEvaluation will return for a given aggId.
    function setEvaluation(
        bytes32 aggId,
        uint256[] calldata scores,
        string calldata justCids,
        bool exists
    ) external {
        _results[aggId] = Result(scores, justCids, exists);
    }

    function setFeeMultiplier(uint256 m) external {
        feeMultiplier = m;
    }

    /// @dev Set how much of each request's prepay is credited back as an ethOwed refund.
    ///      Must be <= the msg.value attached to the request for the mock to stay solvent.
    function setRefundAmount(uint256 amount) external {
        refundAmount = amount;
    }

    /// @dev When true, the prepay refund is credited at finalizeEvaluationTimeout (settlement)
    ///      instead of at request time — used to test the force-fail recovery path.
    function setCreditOnTimeout(bool v) external {
        creditOnTimeout = v;
    }

    // --- IVerdiktaAggregator implementation ---

    function requestAIEvaluationWithApproval(
        string[] memory,
        string memory,
        uint256,
        uint256,
        uint256,
        uint256,
        uint64
    ) external payable returns (bytes32 requestId) {
        _nonce++;
        requestId = keccak256(abi.encodePacked(_nonce, msg.sender));
        requesterOf[requestId] = msg.sender;
        // Default: settle at fulfillment — credit the unspent prepay refund now.
        // With creditOnTimeout, the prepay stays "reserved" until finalizeEvaluationTimeout.
        if (refundAmount > 0 && !creditOnTimeout) {
            ethOwed[msg.sender] += refundAmount;
        }
    }

    function getEvaluation(bytes32 _requestId)
        external
        view
        returns (uint256[] memory, string memory, bool)
    {
        Result storage r = _results[_requestId];
        return (r.scores, r.justificationCids, r.exists);
    }

    function maxTotalFee(uint256 requestedMaxOracleFee) external view returns (uint256) {
        return requestedMaxOracleFee * feeMultiplier;
    }

    // ethOwed(address) getter is auto-generated by the public `ethOwed` mapping.

    function withdrawEth() external {
        uint256 amt = ethOwed[msg.sender];
        require(amt > 0, "nothing owed");
        ethOwed[msg.sender] = 0;
        (bool ok,) = payable(msg.sender).call{value: amt}("");
        require(ok, "withdraw failed");
    }

    function responseTimeoutSeconds() external pure returns (uint256) {
        return 300;
    }

    function finalizeEvaluationTimeout(bytes32 aggId) external {
        // Simulate the aggregator settling a timed-out round: refund the unspent prepay
        // to the original requester's (EvaluationWallet) pull credit, exactly once.
        if (creditOnTimeout && !settled[aggId] && refundAmount > 0) {
            ethOwed[requesterOf[aggId]] += refundAmount;
            settled[aggId] = true;
        }
    }

    receive() external payable {}
}
